-- ==============================================================================
-- Supabase Database Migration: Verified Customer Reviews & 5-Star Ratings System
-- File: supabase/migrations/20260731_product_reviews.sql
-- ==============================================================================
-- 
-- INSTRUCTIONS FOR RUNNING IN SUPABASE SQL EDITOR:
-- 1. Log in to your Supabase Dashboard: https://supabase.com/dashboard
-- 2. Select your project and navigate to "SQL Editor" in the left sidebar menu.
-- 3. Click "+ New query".
-- 4. Copy and paste the entire SQL content of this file into the editor.
-- 5. Click "Run" (or press Ctrl+Enter) to execute the migration.
-- ==============================================================================

-- 1. Create reviews table
CREATE TABLE IF NOT EXISTS public.reviews (
  id                bigint generated by default as identity primary key,
  product_id        text not null,
  customer_name     text not null,
  customer_email    text,
  rating            integer not null check (rating >= 1 and rating <= 5),
  comment           text,
  photo_url         text,
  is_verified_buyer boolean default true,
  is_approved       boolean default true,
  created_at        timestamptz not null default now()
);

-- Ensure columns exist if the table was previously created with fewer columns
ALTER TABLE public.reviews ADD COLUMN IF NOT EXISTS customer_email text;
ALTER TABLE public.reviews ADD COLUMN IF NOT EXISTS photo_url text;
ALTER TABLE public.reviews ADD COLUMN IF NOT EXISTS is_verified_buyer boolean DEFAULT true;
ALTER TABLE public.reviews ADD COLUMN IF NOT EXISTS is_approved boolean DEFAULT true;

-- Performance indexes for querying reviews by product_id and approval status
CREATE INDEX IF NOT EXISTS idx_reviews_product_id ON public.reviews(product_id);
CREATE INDEX IF NOT EXISTS idx_reviews_is_approved ON public.reviews(is_approved);

-- 2. Enable Row Level Security
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies
DROP POLICY IF EXISTS "Allow public read approved reviews" ON public.reviews;
DROP POLICY IF EXISTS "Allow public insert reviews" ON public.reviews;
DROP POLICY IF EXISTS "Allow service role all on reviews" ON public.reviews;

CREATE POLICY "Allow public read approved reviews"
  ON public.reviews FOR SELECT
  TO anon
  USING (is_approved = true);

CREATE POLICY "Allow public insert reviews"
  ON public.reviews FOR INSERT
  TO anon
  WITH CHECK (true);

CREATE POLICY "Allow service role all on reviews"
  ON public.reviews FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
