-- ==============================================================================
-- Valmont Gadgets — private pending-order creation RPC
--
-- The anon role must not SELECT from public.orders.  A PostgREST
-- `Prefer: return=representation` on a direct INSERT evaluates SELECT RLS on
-- the newly inserted row and fails when the table intentionally has no anon
-- SELECT policy (SQLSTATE 42501).
--
-- This migration makes order creation RPC-only:
--   * create_pending_order() validates the cart and database prices, inserts as
--     its SECURITY DEFINER owner, and returns only {id, order_number} as jsonb.
--   * anon has no orders table policy or table SELECT/INSERT privilege.
--   * the final pg_policies assertions fail the migration if a future policy
--     accidentally makes orders readable/writable by anon or PUBLIC.
--
-- Safe to run after 20260805_valmontpay_pipeline.sql and safe to re-run.
-- ==============================================================================

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Remove any legacy public/anon orders policies.  In particular, do not add a
-- SELECT policy: an anon key must never be able to dump customer orders.
DO $$
DECLARE
  p record;
BEGIN
  FOR p IN
    SELECT policyname
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'orders'
      AND (roles && ARRAY['anon', 'public']::name[])
      AND cmd IN ('SELECT', 'INSERT', 'UPDATE', 'DELETE', 'ALL')
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.orders', p.policyname);
  END LOOP;
END
$$;

-- Preserve the authenticated admin path while keeping anon/PUBLIC out.
DROP POLICY IF EXISTS "Authenticated full access orders" ON public.orders;
CREATE POLICY "Authenticated full access orders"
  ON public.orders FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

-- Explicitly revoke the old direct write/read path as well.  The RPC grant
-- below is the only anon-reachable order-creation entry point.
REVOKE SELECT, INSERT ON TABLE public.orders FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.orders TO authenticated, service_role;

-- ── SECURITY DEFINER RPC: create the Pending order ────────────────────────────
CREATE OR REPLACE FUNCTION public.create_pending_order(
  p_order_number   text,
  p_customer_id   text,
  p_items         jsonb,
  p_subtotal      numeric,
  p_delivery_fee  numeric,
  p_total         numeric,
  p_payment_method text
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_item                  jsonb;
  v_product_id            text;
  v_product_name          text;
  v_product_price         numeric;
  v_quantity              integer;
  v_subtotal              numeric := 0;
  v_canonical_items       jsonb := '[]'::jsonb;
  v_supplied_unit_price   numeric;
  v_supplied_line_total   numeric;
  v_customer_id           text;
  v_order_id              text;
BEGIN
  -- Order references are generated by the server endpoint.  Keep the shape
  -- constrained here too because this function is intentionally callable by
  -- the public anon role.
  IF p_order_number IS NULL
     OR length(btrim(p_order_number)) > 64
     OR btrim(p_order_number) !~ '^VG-[A-Z0-9]+-[A-Z0-9]{9}$' THEN
    RAISE EXCEPTION USING
      ERRCODE = '22023',
      MESSAGE = 'invalid order_number';
  END IF;

  IF p_payment_method IS NULL
     OR length(btrim(p_payment_method)) = 0
     OR length(btrim(p_payment_method)) > 60 THEN
    RAISE EXCEPTION USING
      ERRCODE = '22023',
      MESSAGE = 'invalid payment_method';
  END IF;

  IF p_items IS NULL
     OR jsonb_typeof(p_items) <> 'array'
     OR jsonb_array_length(p_items) = 0
     OR jsonb_array_length(p_items) > 50 THEN
    RAISE EXCEPTION USING
      ERRCODE = '22023',
      MESSAGE = 'items must be a non-empty array of at most 50 entries';
  END IF;

  IF p_delivery_fee IS NULL
     OR p_delivery_fee < 0
     OR p_delivery_fee::text = 'NaN'
     OR p_delivery_fee::text = 'Infinity'
     OR p_delivery_fee::text = '-Infinity' THEN
    RAISE EXCEPTION USING
      ERRCODE = '22023',
      MESSAGE = 'invalid delivery_fee';
  END IF;

  IF p_subtotal IS NULL
     OR p_subtotal < 0
     OR p_subtotal::text = 'NaN'
     OR p_subtotal::text = 'Infinity'
     OR p_subtotal::text = '-Infinity'
     OR p_total IS NULL
     OR p_total < 0
     OR p_total::text = 'NaN'
     OR p_total::text = 'Infinity'
     OR p_total::text = '-Infinity' THEN
    RAISE EXCEPTION USING
      ERRCODE = '22023',
      MESSAGE = 'invalid order totals';
  END IF;

  -- A customer row is best-effort in the endpoint.  Only retain a foreign key
  -- that exists; a transient customer upsert failure must not make checkout
  -- fail or permit an arbitrary customer_id to be stored.
  IF p_customer_id IS NOT NULL AND length(btrim(p_customer_id)) > 120 THEN
    RAISE EXCEPTION USING
      ERRCODE = '22023',
      MESSAGE = 'invalid customer_id';
  END IF;
  SELECT c.id INTO v_customer_id
  FROM public.customers AS c
  WHERE c.id = NULLIF(btrim(p_customer_id), '')
  LIMIT 1;

  -- Re-read every product under the definer owner and construct canonical item
  -- JSON.  The endpoint already reprices from products; this second check keeps
  -- the anon-callable RPC safe if somebody calls it directly.
  FOR v_item IN SELECT value FROM jsonb_array_elements(p_items)
  LOOP
    IF jsonb_typeof(v_item) <> 'object' THEN
      RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'each item must be an object';
    END IF;

    v_product_id := NULLIF(btrim(v_item->>'product_id'), '');
    IF v_product_id IS NULL OR length(v_product_id) > 120 THEN
      RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'each item needs a product_id';
    END IF;

    IF coalesce(v_item->>'quantity', '') !~ '^[1-9][0-9]*$' THEN
      RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'each item needs a positive quantity';
    END IF;
    v_quantity := (v_item->>'quantity')::integer;
    IF v_quantity > 50 THEN
      RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'item quantity exceeds the limit';
    END IF;

    SELECT p.name, round(p.price, 2)
      INTO v_product_name, v_product_price
    FROM public.products AS p
    WHERE p.id = v_product_id
      AND p.is_active = true
      AND p.price > 0
    LIMIT 1;

    IF NOT FOUND THEN
      RAISE EXCEPTION USING
        ERRCODE = '22023',
        MESSAGE = format('product %s is unavailable', v_product_id);
    END IF;

    -- If the caller supplied client-visible prices, they must agree with the
    -- catalog.  Missing values are filled canonically below rather than trusted.
    IF NULLIF(btrim(v_item->>'unit_price'), '') IS NOT NULL THEN
      BEGIN
        v_supplied_unit_price := round((v_item->>'unit_price')::numeric, 2);
      EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN
        RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'invalid item unit_price';
      END;
      IF v_supplied_unit_price <> v_product_price THEN
        RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = format('unit_price mismatch for product %s', v_product_id);
      END IF;
    END IF;

    IF NULLIF(btrim(v_item->>'line_total'), '') IS NOT NULL THEN
      BEGIN
        v_supplied_line_total := round((v_item->>'line_total')::numeric, 2);
      EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN
        RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'invalid item line_total';
      END;
      IF v_supplied_line_total <> round(v_product_price * v_quantity, 2) THEN
        RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = format('line_total mismatch for product %s', v_product_id);
      END IF;
    END IF;

    IF length(coalesce(v_item->>'selected_color', '')) > 60
       OR length(coalesce(v_item->>'selected_storage', '')) > 60 THEN
      RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'selected product option is too long';
    END IF;

    v_subtotal := v_subtotal + (v_product_price * v_quantity);
    v_canonical_items := v_canonical_items || jsonb_build_array(
      jsonb_build_object(
        'product_id', v_product_id,
        'name', v_product_name,
        'quantity', v_quantity,
        'unit_price', v_product_price,
        'line_total', round(v_product_price * v_quantity, 2),
        'selected_color', NULLIF(btrim(v_item->>'selected_color'), ''),
        'selected_storage', NULLIF(btrim(v_item->>'selected_storage'), '')
      )
    );
  END LOOP;

  IF round(p_subtotal, 2) <> round(v_subtotal, 2) THEN
    RAISE EXCEPTION USING
      ERRCODE = '22023',
      MESSAGE = 'subtotal does not match active catalog prices';
  END IF;

  IF round(p_total, 2) <> round(p_subtotal + p_delivery_fee, 2) THEN
    RAISE EXCEPTION USING
      ERRCODE = '22023',
      MESSAGE = 'total does not equal subtotal plus delivery_fee';
  END IF;

  INSERT INTO public.orders (
    order_number,
    customer_id,
    items,
    subtotal,
    delivery_fee,
    total,
    status,
    payment_method
  ) VALUES (
    btrim(p_order_number),
    v_customer_id,
    v_canonical_items,
    round(p_subtotal, 2),
    round(p_delivery_fee, 2),
    round(p_total, 2),
    'Pending',
    btrim(p_payment_method)
  )
  RETURNING id INTO v_order_id;

  RETURN jsonb_build_object(
    'id', v_order_id,
    'order_number', btrim(p_order_number)
  );
END;
$$;

REVOKE ALL ON FUNCTION public.create_pending_order(text, text, jsonb, numeric, numeric, numeric, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_pending_order(text, text, jsonb, numeric, numeric, numeric, text)
  TO anon, authenticated, service_role;

-- ── Policy/privilege regression assertions ───────────────────────────────────
-- These query the live catalog (not a copied policy description), so a future
-- policy edit cannot silently turn the anon key into an orders dump.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'orders'
      AND roles && ARRAY['anon', 'public']::name[]
      AND cmd IN ('SELECT', 'INSERT', 'UPDATE', 'DELETE', 'ALL')
  ) THEN
    RAISE EXCEPTION 'orders must have no anon/PUBLIC table policy; inspect pg_policies';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'orders'
      AND policyname = 'Authenticated full access orders'
      AND cmd = 'ALL'
      AND roles @> ARRAY['authenticated']::name[]
  ) THEN
    RAISE EXCEPTION 'expected authenticated orders admin policy is missing';
  END IF;

  IF NOT has_function_privilege(
    'anon',
    'public.create_pending_order(text,text,jsonb,numeric,numeric,numeric,text)',
    'EXECUTE'
  ) THEN
    RAISE EXCEPTION 'anon must be granted EXECUTE on create_pending_order';
  END IF;
  IF NOT has_function_privilege(
    'authenticated',
    'public.create_pending_order(text,text,jsonb,numeric,numeric,numeric,text)',
    'EXECUTE'
  ) THEN
    RAISE EXCEPTION 'authenticated must be granted EXECUTE on create_pending_order';
  END IF;
  IF NOT has_function_privilege(
    'service_role',
    'public.create_pending_order(text,text,jsonb,numeric,numeric,numeric,text)',
    'EXECUTE'
  ) THEN
    RAISE EXCEPTION 'service_role must be granted EXECUTE on create_pending_order';
  END IF;
END
$$;
